### ISSUE TITLE
Multiple charts

### ISSUE THREAD

**Issue by rogiervandongen** [chartjs/chartjs-plugin-datalabels#69] opened 2018-07-02 14:05 UTC
When using multiple graphs on a single page and only configure the datalabels for use on a single dataset (no globals, no chart wide configuration) in one specific graph, the datalabels implementation crashes and keeps the rest of the javascript code fro running due to an error on the following:

var expando = chart[EXPANDO_KEY];

This evaluation, hence the variable "expando" will be undefined.
Any code depending on this variable, or the existence of chart[EXPANDO_KEY], will inherently fail.

I personally ended up by adding "if (expando === undefined) {return;}" after each of these calls for my report pages to continue working as intended.

Please resolve

**Comment by simonbrunel** [comment] 2018-07-02 14:33
Please provide a jsfiddle that reproduces your issue.

**Comment by simonbrunel** [comment] 2018-07-15 07:40
@rogiervandongen can you post a jsfiddle or a link to the code that generates this issue?

**Comment by simonbrunel** [comment] 2018-07-21 10:15
Closing because no test case provided. Feel free to reopen with the code that reproduces this issue.

**Closed by simonbrunel** 2018-07-21 10:15 UTC
Labels: needs test case, support

**Comment by robertocifuentes** [comment] 2021-06-06 11:26
I'm experiencing the same problem. Is this still relevant in 2021? How do I add a fiddle? should I open a new issue?

**Comment by simonbrunel** [comment] 2021-06-06 14:32
Hi @robertocifuentes. I don't know if it's still relevant because I haven't been able to reproduce the error reported by @rogiervandongen. If you think it's the same issue, you can post a fiddle or codepen or link to a repo that reproduces this issue. Make sure that you use the latest version (1.0.0 for Chart.js 2 or 2.0.0-rc.1 for Chart.js 3).

**Comment by d-k-lippert** [comment] 2023-05-31 10:12
Don't know if this is helping, but the error occurred when i had multiple charts. One chart used datalabels, the other didn't. Everytime I hovered over the chart, that didn't use datalabels triggered the error in the console. I believe the error is related with the registration of the ChartDataLabels. Once I switched from global to local registration the error didn't occure.
Here is an example for local registration: 
```
<template>
  <Bar
    :options="chartOptions"
    :data="chartData"
    :plugins="[ChartDataLabels]"
  />
</template>
<script setup lang="ts">
import { Bar } from 'vue-chartjs'
import {
  Chart as ChartJS,
  Title,
  Tooltip,
  Legend,
  BarElement,
  CategoryScale,
  LinearScale
} from 'chart.js'
import ChartDataLabels from 'chartjs-plugin-datalabels'
ChartJS.register(Title, Tooltip, Legend, BarElement, CategoryScale, LinearScale)
```
So deleting` ChartDataLabels` from `ChartJS.register(Title, Tooltip, Legend, BarElement, CategoryScale, LinearScale, ChartDataLabels)` and passing it as property to the Bar-Component  `:plugins="[ChartDataLabels]"` did the trick
