### ISSUE TITLE
Datalabels not working in Internet Explorer 10

### ISSUE THREAD

**Issue by 012attack** [chartjs/chartjs-plugin-datalabels#85] opened 2018-09-04 05:11 UTC
Datalabels not working in Internet Explorer 10..

**Comment by simonbrunel** [comment] 2018-09-05 09:10
What the error / exception you get in IE10? can you share a jsfiddle that reproduces your issue?

**Comment by 012attack** [comment] 2018-09-05 11:02
not error but datalabels is not displayed at IE 10

**Comment by simonbrunel** [comment] 2018-09-06 08:56
That's because [`window.devicePixelRatio`](/chartjs/chartjs-plugin-datalabels/blob/master/src/utils.js#L8) is not compatible with [IE10](https://caniuse.com/#search=devicePixelRatio). We need a fallback value when `window.devicePixelRatio` is `undefined` (maybe simply default to `1` or try to [compute it from other values](https://stackoverflow.com/a/20204180/8837887)).

**Comment by simonbrunel** [comment] 2018-11-07 15:32
@012attack the issue should be fixed by d80b2bea3da2e08 in master and will be released in [v0.5.0](/chartjs/chartjs-plugin-datalabels/milestone/5).

**Comment by simonbrunel** [comment] 2018-11-07 15:32
@012attack can you please checkout master and confirm that it fixes your issue?

**Comment by 012attack** [comment] 2018-11-07 16:13
Thank you.
But I fixed my issue two month ago by setting default value

**Comment by simonbrunel** [comment] 2018-12-11 14:53
Released in [v0.5.0](/chartjs/chartjs-plugin-datalabels/releases/tag/v0.5.0)

**Closed by simonbrunel** 2018-12-11 14:53 UTC
Labels: bug, resolved
