### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'HALF_PI')     at chartjs.helpers.v3.6.0.js:5

### ISSUE THREAD

**Issue by nezlicodes** [chartjs/chartjs-plugin-datalabels#291] opened 2021-10-26 09:16 UTC
I'm getting this error when trying to use the datalabels plugin

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'HALF_PI')
    at chartjs.helpers.v3.6.0.js:5
```

My code:

```
  import Chart from 'chart.js/auto'
  import ChartDataLabels from 'chartjs-plugin-datalabels'
    new Chart(ctx, {
      plugins: [ChartDataLabels],
      type: 'bar',
      ...
     }
```

I am using :
"chart.js": "^3.5.1",
"chartjs-plugin-datalabels": "^2.0.0",
"snowpack": "^3.8.8",

**Comment by simonbrunel** [comment] 2022-08-03 08:06
Closing since no way to reproduce this issue has been provided (which I guess is related to the use or configuration of snowpack).

**Closed by simonbrunel** 2022-08-03 08:06 UTC
Labels: needs test case
