### ISSUE TITLE
[Feature] Is it possible to use images on labels?

### ISSUE THREAD

**Issue by ed1nh0** [chartjs/chartjs-plugin-datalabels#68] opened 2018-06-29 17:44 UTC
In the following example I can see it's possible to use carets as font icons.
![image](https://user-images.githubusercontent.com/1084257/42106522-b752f874-7baa-11e8-9b9d-a8e7060c0b8c.png)
**Source:** https://chartjs-plugin-datalabels.netlify.com/samples/scriptable/data.html

Is it possible to use bitmap or SVG images also?

**Comment by EmilMoe** [comment] 2018-07-05 00:20
I have this as my plugin code, I think you can modify `formatter`. Maybe with a `:before` CSS class?

```
{
                    anchor: function(context) {
                        return 'end'
                    },
                    align: function(context) {
                        return 'top'
                    },
                    color: function(context) {
                        return '#50a1ff'
                    },
                    font: {
                        weight: 'bold'
                    },
                    formatter: function(value, chart) {
                        return value.label.replace('\n', "\n")
                    },
                    offset: 2,
                    padding: 0
                }
```

**Comment by simonbrunel** [comment] 2018-07-15 08:36
@ed1nh0 sorry for the late reply: it's not possible to use image in labels and I don't plan to support this feature since it would add a lot more complexity (asynchronous image loading, resizing images, positioning images, etc.). As a workaround, you can use font icons (e.g. [Font Awesome](https://fontawesome.com/icons?d=gallery)) ([example](https://jsfiddle.net/simonbrunel/y1ry2cvb/)) which IMO is the best way to integrates icons with this plugin, though it doesn't support multi-color icons.

**Comment by ed1nh0** [comment] 2018-07-16 13:31
@simonbrunel that's ok. Thank you for your response, but I believe that not adding this functionality leaves the library somewhat ingrained. The library has a lot of great features, and that would be a great addition. Fontawesome does not have the kind of image I need, and although it looks similar, I can't rotate it exactly because it's not possible.
Please reconsider having this option.

**Comment by renanBritz** [comment] 2018-07-22 21:13
Hello @simonbrunel !

Thank you for this great plugin!

I'm trying to add icons to labels to indicate weather conditions in a mobile app with ionic. For my use case, your suggestion of using font icons would work, but there is another issue: **The icons are not displayed with the correct aspect ratio**. You can check that out in your own [example](https://jsfiddle.net/simonbrunel/y1ry2cvb/). When you hover the cursor on the label, the icon aspect ratio will become normal.

The problem is even worse in mobile devices (the icons become very deformed).

If there's any workaround, please let me know.

Best Regards!

**Comment by simonbrunel** [comment] 2018-07-22 21:45
@renanBritz icons look fine for me in Chrome / Firefox on Win10 and Chrome for Android. What browsers / platforms are you testing on?

**Comment by simonbrunel** [comment] 2018-07-23 07:44
@renanBritz I can reproduce it, but don't know how to fix it.

Can you please create a new ticket with your previous messages describing this issue?

**Comment by rafaelbiten** [comment] 2019-06-18 03:07
Hi! Do you know of a way to add some html to the labels?
On our case we have labels like: `2 ★` and we'd like to have the ★ in a different colour.

Ideally we'd have something like `2 <span style='color: red'>★</span>` or something like that. We're using `chartjs2` with `react-chartjs-2` but apparently, there's no functionality for this. We're considering rendering the labels in a completely custom way below the chart to go around this limitation.

Thank you

**Comment by alexeigs** [comment] 2020-03-28 16:10
> @ed1nh0 sorry for the late reply: it's not possible to use image in labels and I don't plan to support this feature since it would add a lot more complexity (asynchronous image loading, resizing images, positioning images, etc.). As a workaround, you can use font icons (e.g. [Font Awesome](https://fontawesome.com/icons?d=gallery)) ([example](https://jsfiddle.net/simonbrunel/y1ry2cvb/)) which IMO is the best way to integrates icons with this plugin, though it doesn't support multi-color icons.

@simonbrunel Is there a way to also use materialdesignicons aka mdi-v4 icons via formatter?

**Comment by jenildesai25** [comment] 2020-06-09 22:25
Did anyone I find solution how to put any icon on data. I was trying to put up arrow using html but did not work. Any help would be appreciated. I am using react-chartjs-2

Thank you

**Comment by prasanth-git** [comment] 2020-11-05 05:37
Is there any solution or workaround for the aforementioned feature?

Kindly help!

**Comment by anitr** [comment] 2021-03-09 08:52
I would also need something like that - to add an icon to labels. Still nothing?

**Comment by simonbrunel** [comment] 2021-03-13 22:09
> @rafaelbiten Do you know of a way to add some html to the labels?

That's not possible and I don't plan to support this (see this [comment](https://github.com/chartjs/chartjs-plugin-datalabels/issues/192#issuecomment-727197614)).

> @alexeigs Is there a way to also use materialdesignicons aka mdi-v4 icons via formatter?

I don't see any limitation if you use the [webfont](https://dev.materialdesignicons.com/getting-started/webfont), it should work the same as FA.

**Comment by simonbrunel** [comment] 2021-03-13 22:09
I'm closing this issue since I'm not planning to support drawing images in this plugin.

**Closed by simonbrunel** 2021-03-13 22:09 UTC
Labels: wontfix
