### ISSUE TITLE
Wrong aspect ratio when using icon font in labels

### ISSUE THREAD

**Issue by renanBritz** [chartjs/chartjs-plugin-datalabels#76] opened 2018-07-23 12:24 UTC
Hello!

As I described in #68, when using icon font as labels, the icons will be rendered with a wrong aspect ratio, requiring you to hover, or click the corresponding graph for it to become normal.

[Here](https://prnt.sc/k9npyt) is a comparison image attempting to demonstrate. There are two screenshots. The one on top has the icon with the wrong aspect ratio. The one on the bottom has the correct aspect ratio (after I hover the graph with the cursor).

**I'm using Windows 10, latest Chrome version.**

[Here](https://prnt.sc/k9ntbc) is a screenshot of an ionic app running in android 6.0.1. I'm using Ionicons for the labels. If I touch the graph the label's aspect ratio normalizes.

Best Regards!

**Comment by simonbrunel** [comment] 2018-07-30 19:28
@renanBritz I think you are experiencing [this issue](https://stackoverflow.com/questions/2756575/drawing-text-to-canvas-with-font-face-does-not-work-at-the-first-time#2756611). The first time the chart is updated, the [text width](/chartjs/chartjs-plugin-datalabels/blob/master/src/label.js#L209) is not correctly computed because the font is not loaded yet since nothing has been drawn. When hovering a bar, the chart is re-updated but this time the font is loaded (drawn during the previous update).

**Comment by soothran** [comment] 2018-08-10 09:58
Any work around for this?

**Comment by soothran** [comment] 2018-10-04 07:09
Preloading font doesn't worked for me

**Comment by simonbrunel** [comment] 2018-11-24 16:12
> @soothran Having an element styled with the font before the canvas [...] doesn't fix the issue.

> @net Preloading font doesn't worked for me

Can you guys share a fiddle that reproduces your issues?

**Comment by simonbrunel** [comment] 2018-12-21 17:33
@renanBritz @net @soothran unfortunately, this issue seems almost impossible to fix directly in this plugin without complicated and dubious workarounds that would certainly cause more problems than benefits. That's why I will close this ticket as "won't fix". I'm still open for suggestions if it doesn't require to manipulate the DOM, neither relies on custom APIs not available in all browsers supported by Chart.js.

As a workaround (tested in Edge, Chrome, Firefox and IE11), you can pre-load the font in a DOM element **and** wait for the `onload` window event ([fiddle](https://jsfiddle.net/simonbrunel/y1ry2cvb/)):

```html
<canvas id="chart"></canvas>

<!-- WORKAROUND pre-load font resources -->
<div style="font-family: 'FontAwesome'; opacity: 0; height: 0; width: 0">.</div>

<script>
// WORKAROUND wait for the resources to be loaded
window.onload = function() {
    new Chart('chart', {
        options: {
            plugins: {
                datalabels: {
                    font: {
                        family: 'FontAwesome'
                    }
                }
            }
        }       
    });
}
</script>
```

**Closed by simonbrunel** 2018-12-21 17:33 UTC
Labels: bug

**Comment by charleskoehl** [comment] 2019-03-24 20:04
In my react app, just had to add the div from @simonbrunel 's comment to the body of the html containing the react root div:

`<div style="font-family: 'FontAwesome'; opacity: 0; height: 0; width: 0">&nbsp;</div>`

**Comment by bernhardberger** [comment] 2020-11-19 13:59
There are 2 more practicable solutions:

1) use `document.fonts.ready` (not supported in IE11)
```javascript
   document.fonts.ready.then(() => {
      this.renderChart(datacollection, options)
    });
```

2) use `fontfaceobserver` (IE11 compatible): https://github.com/bramstein/fontfaceobserver
```javascript
import FontFaceObserver from 'fontfaceobserver'

const fontFaceObserver = new FontFaceObserver('My Custom Font', {
      weight: 400
    });

    fontFaceObserver.load().then(() => {
      this.renderChart(datacollection, options)
    }, function () {
      alert('Can not render charts as custom font is unavailable');
    });
```
