### ISSUE TITLE
Labels:  anchor, align, in mixed charts

### ISSUE THREAD

**Issue by webmeier** [chartjs/chartjs-plugin-datalabels#15] opened 2017-11-20 12:51 UTC
Hello thank you for your plugin there is a gap by displaying labels in mixed charts looks like a bug when the axis min is not 0, the label is at the bar bottom, but the bar bottom is out of the canvas (clipped)
[https://jsfiddle.net/bistok/1h4nhtq2/6/](https://jsfiddle.net/bistok/1h4nhtq2/6/)
**i want to have the barlabels  at the start of the bars but the start is out of canvas?**
> Edit(SB): fix link

**Comment by simonbrunel** [comment] 2017-11-20 13:18
Your jsfiddle doesn't seem to reproduce your issue, can you update it to make it simpler and obvious what the problem is? (and so remove everything not related to your issue)

**Comment by simonbrunel** [comment] 2017-11-20 14:04
Thanks @webmeier (here is a even simpler [jsfiddle](https://jsfiddle.net/1h4nhtq2/7/))

**Comment by simonbrunel** [comment] 2017-12-17 10:52
I'm not sure where it should be fixed, the issue being that Chart.js creates (visual) bars always starting from the zero value, even if the scale origin is not zero, meaning that the bar base in this case is way out the canvas. So when trying to position the label on the bar with `anchor: 'start'` the label is naturally out of the canvas too.

@etimberg what do you think, should we try to fix it in the bar controller to make sure that bars coordinates are always within the display range? (isn't it too risky?) or should this plugin try to workaround that case?

**Comment by simonbrunel** [comment] 2018-11-02 14:56
I'm closing this issue in favor of #98, which provide a better description and solution in comments.

Thanks @webmeier for reporting this issue.

**Closed by simonbrunel** 2018-11-02 14:56 UTC
Labels: bug

**Comment by simonbrunel** [comment] 2018-11-06 20:46
@webmeier It's finally fixed in #99 (1 year later) and will be released in [v0.5.0](/chartjs/chartjs-plugin-datalabels/milestone/5)
