### ISSUE TITLE
Floating bar chart support

### ISSUE THREAD

**Issue by multiplegeorges** [chartjs/chartjs-plugin-datalabels#139] opened 2019-07-04 18:43 UTC
Hi there,

Is there a plan to support the newly merged floating bar chart type? 
See here: https://github.com/chartjs/Chart.js/pull/6056

Thanks, great set of libraries!

**Comment by marcuswindecker** [comment] 2019-07-08 20:25
It would be amazing to see support added for the PR that @multiplegeorges linked above!

**Comment by simonbrunel** [comment] 2019-07-27 09:30
@multiplegeorges it should already be supported, can you please create a codepen that reproduces the issue you are mentioning?

**Comment by simonbrunel** [comment] 2019-07-28 11:25
I just tested and it works for me with floating bars.

**Comment by simonbrunel** [comment] 2019-08-20 17:41
Closing since it seems to work correctly. Feel free to re-open with a way to reproduce the issue you are experiencing with this kind of charts.

**Closed by simonbrunel** 2019-08-20 17:41 UTC
Labels: needs test case, support
