### ISSUE TITLE
Question: Custom labels for grouped datasets

### ISSUE THREAD

**Issue by jurgenj** [chartjs/chartjs-plugin-datalabels#156] opened 2019-11-03 07:57 UTC
Hi! Firstly - very nice plugin, thank you for that!
I have an issue, which may be easily just a rookie problem but didn't find a solution yet.

I need to use custom labels. If I have a single dataset, everything works like a charm.
I just use
`                    percent: {
                        formatter: function(value, context) {
                         return percentLabels[context.dataIndex] + '%';
                        }
`
where percentLabels is the array of custom labels I want to include.

Now in the other use case is need to have several datasets per one bar chart. Again, I want to add custom label to each single bar on the whole chart. Now the custom labels are again in a single array and they are exactly in the right order for the chart.
What I am trying to understand is if there is some straightforward way to address each bar on the chart individually when I have several data sets. Because when using context.dataIndex, then each bar in the same dataset gets the same custom value - as dataIndex gives me index of dataset, not index of each individual bar from 0-n which I would need.
With dataset.Index it seems I can address bar inside a set but ideally I'd have index from 0-n across all datasets meaning first bar of first dataset is 0 and last bar of last dataset is n.
There might be some longer paths to get to this result but maybe there is a shortcut?

Thanks!

**Comment by simonbrunel** [comment] 2020-05-23 15:08
Hi @jurgenj, sorry for the late reply. In case you still have problem implementing this use case, please create a codepen that reproduces your issue because I'm not sure to understand where it doesn't work. The `context` object contains both data index (the individual bars) and dataset index.

> ... as dataIndex gives me index of dataset

`context.dataIndex` should give you the index of each bar, not the dataset.

```js
labels: {
  percent: {
    formatter: (value, ctx) => {
       // Use ctx.datasetIndex and ctx.dataIndex to access the label
       // from you percentLabels data source. For example:
       return percentLabels[context.datasetIndex][context.dataIndex] + '%';
    }
  }
}
```

I will close this issue but feel free to re-open with a test case.

**Closed by simonbrunel** 2020-05-23 15:08 UTC
Labels: needs test case, support
