### ISSUE TITLE
Overlapping labels with scatter chart

### ISSUE THREAD

**Issue by fishjh2** [chartjs/chartjs-plugin-datalabels#55] opened 2018-05-06 21:57 UTC
Hi, 
I'm using the plugin with scatter charts and it's doing a great job. However, if there are two scatter points very close together the labels often overlap. Is there any way to avoid this?

Thanks a lot

**Comment by orchestor** [comment] 2018-06-07 22:14
Could you help provide a codepen link for debugging.

**Comment by simonbrunel** [comment] 2018-06-30 07:45
There is nothing built-in (yet?) to prevent labels to overlap.

**Comment by simonbrunel** [comment] 2018-11-22 20:39
Closing this one as duplicate of #72

**Closed by simonbrunel** 2018-11-22 20:39 UTC
Labels: duplicate, needs test case
