### ISSUE TITLE
Quasar Support

### ISSUE THREAD

**Issue by bernard-uerm** [chartjs/chartjs-plugin-datalabels#256] opened 2021-06-11 02:08 UTC
Hi, thanks for your hardwork, do you have support for Quasar Framework? I installed vue-chart-js and chartjs works but the chartjs-plugin-datalabels is not working. I've recently developed this using the Vue CLI and it works there but it doesn't work here on Quasar. Any recommendations will help. Thank you very much.

**Comment by simonbrunel** [comment] 2021-07-01 06:52
*"it doesn't work here on Quasar"* doesn't help us to understand your issue.

This plugin works with Vue applications so it's likely an issue with either the `vue-chart-js` integration, the Quasar framework or your code. Since it's not specific to this plugin, **please first ask support from one of these projects**. If there is a bug that needs to be fixed in this plugin, please re-open this issue with a reproduction case and a description of the actual issue (e.g. behavior, logs, etc.).

**Closed by simonbrunel** 2021-07-01 06:52 UTC
Labels: support
