### ISSUE TITLE
v1.0.0 click events don't work

### ISSUE THREAD

**Issue by mikesimmersion** [chartjs/chartjs-plugin-datalabels#243] opened 2021-04-29 20:19 UTC
I am pretty sure I configured everything correctly. It just seems like there is a layer above the chart or something that is intercepting the events. I imagine there is got to be something in the configuration that is wrong that needs to be spelled out in the docs. 

I am using Chart JS 2.9.4
ChartJS-Plugin-Datalabels 1.0.0
Vue-ChartJS 3.5.1

My chart options:

```js
options= {
  maintainAspectRatio: false,
  events: ['mousemove', 'mouseout', 'click', 'touchstart', 'touchmove'],
  plugins: {
    datalabels: {
      display: true,
      align: 'bottom',
      backgroundColor: '#ccc',
      borderRadius: 3,
      font: {
        size: 18,
      }
    }
  },
  legend: {
    position: 'top',
  },
  scales: {
    xAxes: [{
      stacked:true
    }],
    yAxes: [{
      stacked:true
    }]
  },
  animation: {
    animateScale: true,
    animateRotate: true
  }
};
```
  
My dataset configuration:

```js
var data= {
  datasets: [{
    label: "Not Started",
    data: [1],
    datalabels: {
      listeners: {
        click: function(context) {
          console.log('label b' + context.dataIndex + ' has been clicked!');
        }
      }
    }
  }, {
    label: "Started",
    data: [1],
    datalabels: {
      listeners: {
        click: function(context) {
          console.log('label b' + context.dataIndex + ' has been clicked!');
        }
      }
    }
  }, {
    label: "Completed",
    data: [1],
    datalabels: {
      listeners: {
        click: function(context) {
          console.log('label b' + context.dataIndex + ' has been clicked!');
        }
      }
    }
  }],
  labels: ['Lesson 1']
};
```

**Comment by simonbrunel** [comment] 2021-05-03 18:37
@mikesimmersion I don't see anything wrong in your code but without a working example, it's hard to help. Please provide us a jsfiddle or codepen that reproduces your issue so we can debug it.

**Comment by mikesimmersion** [comment] 2021-05-03 19:28
I did some further testing and determined that the issue appears only when using Vue.js. Click events worked when running a vanilla JS example, but when I ran it in the Vue framework they no longer worked:

JS fiddle:
https://jsfiddle.net/z1kL95nd/1/

**Comment by simonbrunel** [comment] 2021-05-03 19:58
It's an issue with Chart.js 2.9.4 (see [this link](https://stackoverflow.com/a/66058308/8837887)). But note that your `clone` implementation is wrong because you rely on `JSON.stringify()`, which doesn't support functions: the `click` handler is a function, thus get lost during the conversion.

The main problem is storing your chart config in the Vue.js `data`, making it reactive, which is not anymore supported in Chart.js 2.9.4. You should either not store the Chart config in the `data` or downgrade to Chart.js 2.9.3. Maybe you could have a look at [this code](https://github.com/simonbrunel/vuepress-theme-chartjs/blob/main/components/ChartView.vue#L15), it may help you to workaround this Chart.js issue.

I'm closing this issue since it's not related to this plugin.

**Closed by simonbrunel** 2021-05-03 19:58 UTC
Labels: invalid
