### ISSUE TITLE
Datalabel doesn't dissapear after hiding bar chart by clicking legend label

### ISSUE THREAD

**Issue by Ghost180195** [chartjs/chartjs-plugin-datalabels#77] opened 2018-08-02 19:36 UTC
Browser version: Google Chrome 68
OS version: Windows 10
Charjs version: 2.7.2
Chartjs plugin datalabels version: 0.3.0
[CodePen link](https://codepen.io/anon/pen/bjMKGK?editors=1010)

Issues describe:
After clicking legend label for disappearing bar chart datalabel does not dissapear but bar chart dissapears normally.

![screenshot1](https://user-images.githubusercontent.com/31181880/43606407-aed66d14-96b4-11e8-811c-321d9f13f35c.png)

Also there is another issue. 
Datalabel goes beyond schedule

![screenshot2](https://user-images.githubusercontent.com/31181880/43606500-fa2eba5a-96b4-11e8-9f57-fe047909c561.png)

Can I make it so that the datalabel has moved to the body of the bar chart if the datalabel  goes beyond schedule?

**Comment by simonbrunel** [comment] 2018-08-03 08:45
@Ghost180195 this issue has already been reported in #51 and fixed in [v0.4.0](/chartjs/chartjs-plugin-datalabels/releases/tag/v0.4.0) released today ([fiddle](https://codepen.io/anon/pen/WKyNzr))

> Can I make it so that the datalabel has moved to the body of the bar chart...

No built-in solution. You could write a scriptable option for `align` that checks if your value is below a certain threshold, but that doesn't scale very well. I'm planning to introduce a new `constrain` option that will make sure the label stays inside the chart area but it's definitely not ready. If you think of another API that could help to fix this case, please open a new "feature" ticket describing exactly the behavior you are expecting so we can discuss about it.

I'm closing this tickets as duplicate of #51

**Closed by simonbrunel** 2018-08-03 08:45 UTC
Labels: duplicate, resolved

**Comment by Ghost180195** [comment] 2018-08-03 09:39
Thanks for you answer.
I have a question. How can i get suggestedMax number s(for example in the image it is 4000 for legend2 and it is 400 fro legend1)?
