### ISSUE TITLE
Anchor is always set to end (in node.js)

### ISSUE THREAD

**Issue by artdomg** [chartjs/chartjs-plugin-datalabels#185] opened 2020-07-07 15:19 UTC
Not setting anchor (it's supposed to be center by default), setting it to start or center doesn't work. It is always in the end of the chart.

Alignment works, anchor doesn't.

![image](https://user-images.githubusercontent.com/1509082/86803228-a3f31e00-c02a-11ea-8f21-b9d5295f54f8.png)

![image](https://user-images.githubusercontent.com/1509082/86803042-7a39f700-c02a-11ea-8a83-70a2d0bc85aa.png)

Using:
- chart.js v2.9.3
- chartjs-plugin-datalabels v0.7.0
- bar / horizontalBar charts
- chartjs-node-canvas v3.0.6

Note: This works on Chart.js v2.7.3

**Comment by gemini86** [comment] 2020-07-20 22:30
I'm also having this issue, but have managed to get it to work randomly. Mostly it will work on my local machine, but then when publishing a package and installing from npm on another machine, this problem occurs.

**Comment by simonbrunel** [comment] 2020-11-15 11:38
@artdomg Late answer, I hope you found a way to make it work. Do you have any min/max set on your horizontal scale? If so, that means your bar is actually bigger than what we see on your screenshot, thus the label is anchored at the center but of the whole bar. In that case, you can use the [`clamp` option](https://chartjs-plugin-datalabels.netlify.app/guide/positioning.html#clamping). If it still doesn't work, please provide us a way to reproduce your issue.

**Comment by simonbrunel** [comment] 2020-12-23 10:25
I'm closing this issue since there is no codepen / repo that we can use to reproduce it. If it still doesn't work, please re-open this ticket with a link to the sources that we can use to debug it.

**Closed by simonbrunel** 2020-12-23 10:25 UTC
Labels: needs test case

**Comment by AleeeKoi** [comment] 2024-02-16 20:05
Hi @artdomg , did you resolve it?
Using the same versions the label still stuck at the end of the horizontal bar.

![image](https://github.com/chartjs/chartjs-plugin-datalabels/assets/46484371/ee30569f-4aa2-47a0-8dff-7ea25a91cc63)
