### ISSUE TITLE
Draw order incorrect if empty (null) values in dataset

### ISSUE THREAD

**Issue by LaurentCargill** [chartjs/chartjs-plugin-datalabels#319] opened 2022-06-09 14:06 UTC
When applying data labels to a radar chart, the z-index and draw order becomes out of sync if there are null/empty values in the data set.

<img width="785" alt="image" src="https://user-images.githubusercontent.com/31843753/172866593-32b5d78d-676f-4afa-b6c9-fa8af00d6c14.png">

**Comment by simonbrunel** [comment] 2022-06-09 14:22
Hi @LaurentCargill. Can you provide a Codepen that reproduces your issue so it's easier for us to debug it?

**Comment by LaurentCargill** [comment] 2022-06-09 14:53
https://codepen.io/laurentcargill/pen/ExQdONO

A null value added to series 2 results in subsequent data points to be drawn on top of series 1, not below it.

**Comment by stockiNail** [comment] 2022-06-10 17:58
@simonbrunel I think the issue should be related to the fact that when a data element has `skip` property, the label object is not created (condition `!el.skip`). 

https://github.com/chartjs/chartjs-plugin-datalabels/blob/cdc2e94837a10d19eb1fc86996a271a298821b13/src/plugin.js#L181

Due to that, when the array of labels to draw is created and sorted, when an item is missing, the sequence of drawing changes. By default, the labels are drawn starting from the last dataset to the first but missing an item in the array, the sequence changes.

https://github.com/chartjs/chartjs-plugin-datalabels/blob/cdc2e94837a10d19eb1fc86996a271a298821b13/src/layout.js#L96-L129

I think could make sense to manage labels even if the related element is skipped.

**Comment by simonbrunel** [comment] 2022-08-03 07:29
Fixed in #323 and released in [v2.1.0](https://github.com/chartjs/chartjs-plugin-datalabels/releases/tag/v2.1.0) (thanks @stockiNail)

**Closed by simonbrunel** 2022-08-03 07:29 UTC
Labels: bug, resolved
