### ISSUE TITLE
formatter not hide onclick legend bar chart

### ISSUE THREAD

**Issue by exyear** [chartjs/chartjs-plugin-datalabels#66] opened 2018-06-25 08:19 UTC
Formatter Not Hide when onclick legend on bar chart

**Comment by simonbrunel** [comment] 2018-06-25 08:58
Please elaborate your issue and add a jsfiddle that demonstrates the problem.

**Comment by adamsow** [comment] 2018-07-04 12:33
I think what  @exyear have in mind is that labels are still visible after crossing out one of datasets. Have similar issue here:
![image](https://user-images.githubusercontent.com/23338087/42277149-aafbb0f8-7f96-11e8-80f1-be71f93c16bc.png)

and when click one dataset in the legend bars are no more, but labels are still visible:
![image](https://user-images.githubusercontent.com/23338087/42277317-41220c44-7f97-11e8-96c5-50bead0c1c3d.png)

**Comment by simonbrunel** [comment] 2018-07-04 12:39
Thanks @adamsow 

Closing as duplicate of #51 (fixed in master, will be released in 0.4.0)

**Closed by simonbrunel** 2018-07-04 12:39 UTC
Labels: duplicate, needs test case
