### ISSUE TITLE
TypeScript definition for dataset and plugin options

### ISSUE THREAD

**Issue by Laroosta** [chartjs/chartjs-plugin-datalabels#105] opened 2018-12-14 13:46 UTC
Hi,

I'm currently getting typing errors when adding datalabels to a dataset, which is then preventing the app to compile.

If I manually add the datalabels properties in the @types/chart.js file, it works fine, but this is not a proper solutions, as one should not add specific properties to the chart.js typings library for a plugin.

For now I had to duplicate the chart.js typings and add them as a typeRoots to the project. This means that the typings need to maintained locally.

Does anyone know how this problem can be solved? Is it not possible to extend the chart.js typings and add the plugin specific properties?

**Comment by simonbrunel** [comment] 2018-12-14 14:07
@Laroosta can you share a minimal project that reproduces this issue and instructions to build it?

**Comment by Laroosta** [comment] 2018-12-16 12:33
Hi Simon,

Thank you so much for taking the time to respond. I will use your
suggestion until the typing definitions get updated.

Kind regards
Leroux

**Comment by simonbrunel** [comment] 2019-01-30 15:06
TypeScript definition files added in 2d9424ab3dc8185f9c531ad8af85c8eaab7c4099, will be released in [v0.6.0](/chartjs/chartjs-plugin-datalabels/milestone/7)

**Comment by RiQuY** [comment] 2019-03-13 09:38
This would be very useful, the v0.6.0 is far from be released?

**Comment by simonbrunel** [comment] 2019-03-13 09:54
v0.6.0 is about to be released (probably this week)

> do you know a way to apply this to a project on TypeScript that I'm working on before v0.6.0 release?

No, I don't (I don't use TypeScript myself)

> Would this be added to DefinitelyTyped ... ?

I don't think so because it will conflict with the one in this repository.

**Comment by simonbrunel** [comment] 2019-03-14 14:15
Version [0.6.0](https://github.com/chartjs/chartjs-plugin-datalabels/releases/tag/v0.6.0) has been released.

**Closed by simonbrunel** 2019-03-14 14:15 UTC
Labels: enhancement, resolved
