### ISSUE TITLE
Persistent labels when interacting with chart

### ISSUE THREAD

**Issue by DavidsInferno** [chartjs/chartjs-plugin-datalabels#207] opened 2020-12-21 17:05 UTC
When I disable one bar in a bar chart the label is still in the same position and as the bar fills over that location you can see the label of the bar that is disabled.

Normal:
![image](https://user-images.githubusercontent.com/26233887/102802462-f8127480-43b6-11eb-97f8-978aa9769480.png)

Disabled first bar:
![image](https://user-images.githubusercontent.com/26233887/102802449-ed57df80-43b6-11eb-9f64-6a773858e957.png)

Disabled second bar:
![image](https://user-images.githubusercontent.com/26233887/102802424-e29d4a80-43b6-11eb-830e-6222d86f2a97.png)

**Comment by simonbrunel** [comment] 2020-12-21 19:20
@DavidsInferno can you create a codepen (or similar) that reproduces this issue?

**Comment by DavidsInferno** [comment] 2020-12-22 09:03
I have a problem with getting it to look the same, but thats basically the code I am using.

[https://codepen.io/davidsinferno/pen/dypzBaJ](url)

**Comment by simonbrunel** [comment] 2020-12-22 09:24
It works as expected with the latest version: https://codepen.io/simonbrunel/pen/bGwrXvV

**Comment by simonbrunel** [comment] 2020-12-22 09:33
I think you still use an old version: this issue was reported in #51 and #77 and have been fixed in [v0.4.0](https://github.com/chartjs/chartjs-plugin-datalabels/releases/tag/v0.4.0) (542ec921c2362d9075cc6a7e324d22df560844ce). 

Try to update to the latest version (v0.7.0).

**Comment by DavidsInferno** [comment] 2020-12-22 09:37
I am already using the latest versions

![image](https://user-images.githubusercontent.com/26233887/102873569-99460d00-4441-11eb-91bf-e505ebe5a3ac.png)

**Comment by simonbrunel** [comment] 2020-12-22 10:19
As shown in my codepen, it works as expected when hiding bars with v0.7.0, so you may have a different setup. Unfortunately, your codepen doesn't run correctly (invalid plugin script URL) and without a way to reproduce your issue, we can't help further.

**Comment by simonbrunel** [comment] 2020-12-30 18:26
Closing since we have no way to reproduce your issue.

**Closed by simonbrunel** 2020-12-30 18:26 UTC
Labels: needs test case
