### ISSUE TITLE
Overlay label on top of each other.

### ISSUE THREAD

**Issue by rruvaleev** [chartjs/chartjs-plugin-datalabels#182] opened 2020-05-28 07:50 UTC
Overlay label on top of each other.
How can I configure padding?
![Снимок экрана от 2020-05-28 12-48-42](https://user-images.githubusercontent.com/63503409/83113899-ad12d600-a0e1-11ea-97e1-2eb7c523c753.png)

**Comment by simonbrunel** [comment] 2020-11-15 11:48
Probably a duplicate of #72 and/or #81. As a workaround, you could use the same solution as in [this example](https://chartjs-plugin-datalabels.netlify.app/samples/scriptable/dataset.html) ([source](https://github.com/chartjs/chartjs-plugin-datalabels/blob/master/samples/scriptable/dataset.html#L97)). It would make sure to align the yellow & blue labels at the opposite.

**Closed by simonbrunel** 2020-11-15 11:48 UTC
Labels: duplicate
