### ISSUE TITLE
[ask] get error from script source

### ISSUE THREAD

**Issue by edwinnsan** [chartjs/chartjs-plugin-datalabels#113] opened 2019-02-06 03:26 UTC
hello, i try this plugin on my html, but when i put the script then reload the page, i get 2 error like this..
![screenshot from 2019-02-06 10-25-52](https://user-images.githubusercontent.com/17553775/52318955-a39bc100-29f9-11e9-82d4-5bf06e083230.png)
![screenshot from 2019-02-06 10-18-49](https://user-images.githubusercontent.com/17553775/52318958-a5fe1b00-29f9-11e9-8937-7994e3253a85.png)

do you guys know why this happen? Thanks!

**Comment by simonbrunel** [comment] 2019-02-06 06:54
@edwinnsan can you please share your HTML page or a jsfiddle that reproduces your issue?

**Comment by simonbrunel** [comment] 2019-02-07 21:02
@edwinnsan any update on that issue?

**Comment by simonbrunel** [comment] 2019-02-09 08:14
Closing because we can't investigate your issue without a way to reproduce it. Feel free to reopen if you can provide us the code that generates this error.

**Closed by simonbrunel** 2019-02-09 08:14 UTC
Labels: needs test case
