### ISSUE TITLE
Plugin disables canvas reference in Vuejs

### ISSUE THREAD

**Issue by eduardobcastro** [chartjs/chartjs-plugin-datalabels#47] opened 2018-04-02 18:52 UTC
Everything was fine but when I added the datalabels plugin (as described in #10) then I started getting this error
```
BaseCharts.js?a889:56 Uncaught (in promise) TypeError: Cannot read property 'getContext' of undefined
    at VueComponent.renderChart (BaseCharts.js?a889:56)
    at VueComponent.boundFn [as renderChart] (vue.esm.js?efeb:189)
    at VueComponent._callee$ (BalanceChart.vue?7315:56)
    at tryCatch (runtime.js?4a57:62)
    at Generator.invoke [as _invoke] (runtime.js?4a57:296)
    at Generator.prototype.(:8080/anonymous function) [as next] (webpack-internal:///./node_modules/regenerator-runtime/runtime.js:114:21)
    at step (asyncToGenerator.js?7b11:17)
    at eval (asyncToGenerator.js?7b11:28)
```

BaseCharts.js
```
      renderChart: function renderChart(data, options) {
        this.$data._chart = new Chart(this.$refs.canvas.getContext('2d'), {
...
```

**Comment by simonbrunel** [comment] 2018-04-03 13:04
I see no reason why this plugin would invalidate `this.$refs.canvas`. Unfortunately I can't say what's going on without more context, please share a **minimal** Vue.js project that reproduces this issue.

**Comment by simonbrunel** [comment] 2018-04-22 08:33
@eduardobcastro I'm closing this issue since without any decent test case, I can't investigate this error.

Feel free to re-open if you can provide (much) more information.

**Closed by simonbrunel** 2018-04-22 08:33 UTC
Labels: needs test case, support
